version: 1.0.0-alpha {build}
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
environment:
  COVERITY_TOKEN:
    secure: mA6wJn6L7DKI0htEOrL5mXFktc4boBafgMN7vLLNGbI=
  COVERITY_EMAIL:
    secure: 6zUyb+IRQkAbWNWP0T0sHw==
  CODECOV_TOKEN:
    secure: 2dCIzLRKIcRbsQbsYVPWaCxY2JIN1t3ELY0fFIrDXsBBbZ2zqCl8s2o8YXIh8DRk
  SONARQUBE_TOKEN:
    secure: B8SjYjO+rTDRb265vIqaCU5D9/DdbwpqD2EyzZJl3lzAqIzI/xvsva6ivN1ZHMu1
install:
- ps: >-
    #Install-Package -Force MSBuild.SonarQube.Runner.Tool

    (New-Object System.Net.WebClient).DownloadFile(
      "https://repox.sonarsource.com/sonarsource-public-builds/org/sonarsource/scanner/msbuild/sonar-scanner-msbuild/2.3.0.553/sonar-scanner-msbuild-2.3.0.553.zip",
      "$PWD\sonar-scanner-msbuild.zip"
    )

    Expand-Archive $PWD\sonar-scanner-msbuild.zip -DestinationPath $PWD\SonarQube

cache: packages -> **\packages.config
build_script:
- cmd: >-
    nuget restore

    cov-build --dir cov-int msbuild CoverityTestbed.sln /p:UseSharedCompilation=false /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    rem set PATH="C:\Program Files\PackageManagement\NuGet\Packages\MSBuild.SonarQube.Runner.Tool.1.0.0\tools";%PATH%

    set PATH=".\SonarQube";%PATH%

    MSBuild.SonarQube.Runner.exe begin /k:"AnalysisTestbed" /o:"viciousviper-github" /n:"Analysis Testbed" /v:"%APPVEYOR_BUILD_VERSION%" /d:"sonar.language=cs" /d:"sonar.cs.vstest.reportsPaths=CoverityTestbed_testresults.trx" /d:"sonar.cs.opencover.reportsPaths=CoverityTestbed_coverage.xml" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SONARQUBE_TOKEN%"

    MSBuild CoverityTestbed.sln /t:Rebuild /p:UseSharedCompilation=false /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
- cmd: >-
    set PATH=".\packages\OpenCover.4.6.519\tools";%PATH%

    OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" -targetargs:"/noisolation /resultsfile:CoverityTestbed_testresults.trx /testcontainer:.\UnitTests\bin\%CONFIGURATION%\UnitTests.dll" -filter:"+[UnitTests*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:CoverityTestbed_coverage.xml

    MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SONARQUBE_TOKEN%

    curl.exe -d .\CoverityTestbed_testresults.trx https://ci.appveyor.com/api/testresults/mstest/%APPVEYOR_JOB_ID%

    set PATH="C:\Python34;C:\Python34\Scripts";%PATH%

    pip install codecov

    codecov -f .\CoverityTestbed_coverage.xml -X gcov

    IF %CONFIGURATION% NEQ Debug EXIT

    7z a -r coverity.zip cov-int

    curl.exe -F token=%COVERITY_TOKEN% -F email=%COVERITY_EMAIL% -F file=@coverity.zip -F version="1.0.0-alpha" https://scan.coverity.com/builds?project=%APPVEYOR_REPO_NAME%

artifacts:
- path: cov-int/build-log.txt
  name: Coverity Build Log
- path: CoverityTestbed_testresults.trx
  name: TestResults
- path: CoverityTestbed_coverage.xml
  name: Coverage
